"""empty message

Revision ID: 6080873f37d9
Revises: 8920ee375c29
Create Date: 2021-04-23 16:57:53.157070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6080873f37d9'
down_revision = '8920ee375c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cars', sa.Column('photo', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cars', 'photo')
    # ### end Alembic commands ###
