"""empty message

Revision ID: 73a411b2b77d
Revises: b32e02557355
Create Date: 2021-04-23 15:48:34.769573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a411b2b77d'
down_revision = 'b32e02557355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Users_username_key', 'Users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Users_username_key', 'Users', ['username'])
    # ### end Alembic commands ###
